spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_computer_store
    username: root
    password: 753159852
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: COMPUTER-STORE-API